name: Workflow_Test
on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello, world!'
  pwd-ls:
    runs-on: ubuntu-latest
    steps:
      - name: print working directory
        run: pwd
      - name: list flies
        run: ls -al
